name: .NET Core CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Build Docker image
      run: docker build -t myapp .

    - name: Run Docker container
      run: docker run -d -p 80:80 myapp

    - name: Check running containers
      run: docker ps

    # Adicione etapas adicionais conforme necessário
